ALTER TABLE applicants
  ADD COLUMN IF NOT EXISTS name VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS age INT NULL,
  ADD COLUMN IF NOT EXISTS education VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS course VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS positionAppliedFor VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS collectionExperience VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS referral VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS resumeUrl VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS pictureUrl VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS status VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS addedDate VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS addedBy VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS assignedTL VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS assignedUserId INT NULL,
  ADD COLUMN IF NOT EXISTS assignedDate VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS approvedBy VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS approvedDate VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS rejectedBy VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS rejectedDate VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS deletedBy VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS deletedDate VARCHAR(50) NULL;

ALTER TABLE assignments
  ADD COLUMN IF NOT EXISTS applicantId INT NULL,
  ADD COLUMN IF NOT EXISTS applicantName VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS positionAppliedFor VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS tlEmail VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS tlName VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS assignedBy VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS assignedDate VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS status VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS resumeUrl VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS pictureUrl VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS age INT NULL,
  ADD COLUMN IF NOT EXISTS education VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS course VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS collectionExperience VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS referral VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS requestId INT NULL;

ALTER TABLE manpower_requests
  ADD COLUMN IF NOT EXISTS teamLeadEmail VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS teamLeadName VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS tlId INT NULL,
  ADD COLUMN IF NOT EXISTS position VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS requestedCount INT NULL,
  ADD COLUMN IF NOT EXISTS `limit` INT NULL,
  ADD COLUMN IF NOT EXISTS status VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS date VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS pdfUrl VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS assignedCount INT NULL;

CREATE TABLE IF NOT EXISTS audit_logs (
  id INT NOT NULL AUTO_INCREMENT,
  actorUserId INT NOT NULL,
  actorEmail VARCHAR(255) NOT NULL,
  actorRole VARCHAR(50) NOT NULL,
  action VARCHAR(50) NOT NULL,
  entity VARCHAR(50) NOT NULL,
  entityId VARCHAR(50) NOT NULL,
  beforeData LONGTEXT NULL,
  afterData LONGTEXT NULL,
  createdAt DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY ix_audit_entity (entity, entityId),
  KEY ix_audit_actor (actorUserId)
);

CREATE TABLE IF NOT EXISTS sessions (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  token VARCHAR(128) NOT NULL,
  createdAt DATETIME NOT NULL,
  expiresAt DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY ux_sessions_token (token),
  KEY ix_sessions_user (userId)
);
